export default [
  {
    id: 1,
    img: "profile.png",
    rating: 5.0,
    reviewCount: 6,
    location: "USA",
    price: 136,
    title: "Life lessons with Katie Zaferes",
    openSpots: 0,
  },
  {
    id: 2,
    img: "profile.png",
    rating: 10.0,
    reviewCount: 456,
    location: "Online",
    price: 145,
    title: "Life lessons with Katie Zaferes",
    openSpots: 2,
  },
  {
    id: 3,
    img: "profile.png",
    rating: 6.0,
    reviewCount: 123,
    location: "Ireland",
    price: 166,
    title: "Life lessons with Katie Zaferes",
    openSpots: 0,
  },
  {
    id: 4,
    img: "profile.png",
    rating: 10.0,
    reviewCount: 456,
    location: "UK",
    price: 145,
    title: "Life lessons with Katie Zaferes",
    openSpots: 9,
  },
  {
    id: 5,
    img: "profile.png",
    rating: 6.0,
    reviewCount: 123,
    location: "Online",
    price: 166,
    title: "Life lessons with Katie Zaferes",
    openSpots: 9,
  },
  {
    id: 6,
    img: "profile.png",
    rating: 10.0,
    reviewCount: 456,
    location: "UK",
    price: 145,
    title: "Life lessons with Katie Zaferes",
    openSpots: 0,
  },
  {
    id: 7,
    img: "profile.png",
    rating: 6.0,
    reviewCount: 123,
    location: "Ireland",
    price: 166,
    title: "Life lessons with Katie Zaferes",
    openSpots: 3,
  },
];     
        